### ISSUE TITLE
Tweaks to molecule viz menu

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/oc-web-components#71]
@cryos Could you outline the changes you would like to see the molecule viz menu?

**Comment by cryos** [comment]
High level, ability to choose between vtk.js and 3Dmol.js for structure visualization. Should choose reasonable defaults, vtk.js for volumes, 3Dmol.js for vibrational modes.

**Electronic structure/volumes**

Should offer the option to choose the molecular orbital, should mark the HOMO/LUMO in brackets, and we should consider the need to generalize in future to cover electron density. Below that we should offer the isosurface/volume rendering option. If volume rendering is chosen the color-opacity item should be shown, otherwise the isovalue.

Below that a combo would be nice with ball and stick, Van der Waals, stick, or custom where custom could then show the sliders for ball/stick.

**Vibrational Modes**

Chooser for the mode, slider for speed, amplitude, same combo as above for render mode (ball and stick, etc).

I think that covers the basics, it might be good to sketch out the layout, but nothing too major. Main thing I think is enhancing electronic structure options.
